### ISSUE TITLE
Extension Idea: Jupyter integration

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-Extensions-Repository#57]
> Would be useful for people wanting to test out Python programs on their system, with a nice interface (e.g. for testing Navigator library functionalities).
> -@RaulTrombin

Maybe try to integrate jupyter lab (rather than just notebook), on top of a volume/bind for persistent storage?

**Comment by RaulTrombin** [comment]
- [x] https://github.com/bluerobotics/BlueOS-Extensions-Repository/pull/68
