### ISSUE TITLE
Extension: Navigator Webassistant - Not showing on BlueOS bazaar

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/BlueOS-Extensions-Repository#82]
Issue:
The extensions-manager not show the new available extension;
Route http://blueos-wifi.local/kraken/v1.0/extensions_manifest also does not show the new extension;

from local test:
`python3 -m poetry run blueos_repository/consolidate.py`
Result:
```
fetching tags in patrickelectric/blueos-node-red
['1.0.2', '1.0.1', '1.0.0']
fetching labels for patrickelectric/blueos-node-red:1.0.2
fetching labels for patrickelectric/blueos-node-red:1.0.1
fetching labels for patrickelectric/blueos-node-red:1.0.0
fetching tags in patrickelectric/blueos-bb
['master']
master is not valid SemVer, ignoring it...
fetching tags in raulelektron/blueos_navigator_webassistant
['0.0.0', 'latest']
fetching labels for raulelektron/blueos_navigator_webassistant:0.0.0
Error status 404
latest is not valid SemVer, ignoring it...
fetching tags in williangalvani/blueos-extension-proxy
['v1.0.3', 'master', 'iframes', 'v1.0.2', 'nocache', 'websockets', 'v1.0.1', 'v1.0.0', 'v0.0.1']
fetching labels for williangalvani/blueos-extension-proxy:v1.0.3
master is not valid SemVer, ignoring it...
iframes is not valid SemVer, ignoring it...
fetching labels for williangalvani/blueos-extension-proxy:v1.0.2
nocache is not valid SemVer, ignoring it...
websockets is not valid SemVer, ignoring it...
fetching labels for williangalvani/blueos-extension-proxy:v1.0.1
fetching labels for williangalvani/blueos-extension-proxy:v1.0.0
fetching labels for williangalvani/blueos-extension-proxy:v0.0.1
Error status 404
```

**Comment by RaulTrombin** [comment]
@patrickelectric think it's fixed.

Issues found:
1. missing version LABEL
2. position of "Privileged" parameter was inside PortBinding

Question:
LABEL type="education" is valid?
"types" is a free field?

Could you re-run the manifest action?

**Comment by rafaellehmkuhl** [comment]
[Did](https://github.com/bluerobotics/BlueOS-Extensions-Repository/actions/runs/7792221770)

**Comment by RaulTrombin** [comment]
> [Did](https://github.com/bluerobotics/BlueOS-Extensions-Repository/actions/runs/7792221770)

Thks @rafaellehmkuhl 

![image](https://github.com/bluerobotics/BlueOS-Extensions-Repository/assets/80598030/ee23f99c-2cf6-4413-91a1-e7aa106a3e5d)

Extension available, closing issue.
